apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: picalc
  name: picalc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: picalc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: picalc
    spec:
      containers:
      - image: quay.io/sttyerase/picalc:0.1
        name: picalc
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: picalc
  name: picalc
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: picalc
  type: ClusterIP
status:
  loadBalancer: {}
