apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: picalc-deployment
  labels:
    app: picalc
spec:
  selector:
    matchLabels:
      app: picalc
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: picalc
    spec:
      containers:
        - name: picalc
          image: docker.io/dbmidocker/picalc:latest
          ports:
            - containerPort: 8181
